spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/users
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

---
spring:
  profile: test
  datasource:
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver




